name: CD
on:
  push:
    branches:
      - main
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar pruebas
        run: npm test
      - name: Ejecutar ESLint
        run: |
          npm install --save-dev eslint
          npx eslint .
      - name: Desplegar a Render
        run: echo "Aquí va el comando de despliegue a Render (ajusta según tu configuración)"
